spring:
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:vibe-music-server-dev.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 以下敏感信息建议放到 Nacos，或通过环境变量注入
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/vibe_music?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    type: com.alibaba.druid.pool.DruidDataSource # 配置连接池

  # Redis服务连接配置
  data:
    redis:
      database: 1
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  servlet:
    multipart:
      max-file-size: 1000MB # 设置最大上传文件大小为1000MB
      max-request-size: 1000MB # 设置最大请求大小为1000MB

  # 对于注解的Redis缓存数据统一设置有效期为10分钟，单位毫秒
  cache:
    redis:
      time-to-live: 600000

  # 配置邮件服务
  mail:
    # 配置邮箱账户和密码（建议放到 Nacos）
    host: ${MAIL_HOST:smtp.qq.com}
    username: ${MAIL_USERNAME:example@qq.com}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          # 邮件服务超时时间配置
          connectiontimeout: 8000
          timeout: 3000
          writetimeout: 5000

# 配置 mybatis-plus
mybatis-plus:
  type-aliases-package: cn.edu.seig.pojo # 实体类所在的包，允许用实体类类名作为别名

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
    map-underscore-to-camel-case: true # 类属性与表字段的驼峰映射

  global-config:
    db-config: # 数据库配置
      table-prefix: tb_  # 表名前缀为tb_，表名为前缀连接类名（小写）

# YunGou 配置（建议在 Nacos 中覆盖这些值）
yungou:
  #这里用xxx代替，真实的数据已经放入Nacos中
  mch-id: ${YUNGOU_MCH_ID:xxx}
  mch-key: ${YUNGOU_MCH_KEY:xxx}
  callback-url: ${YUNGOU_CALLBACK_URL:http://localhost:8090/}

# 定义角色和路径权限的映射关系
role-path-permissions:
  permissions:
    ROLE_ADMIN:
      - "/admin/"
      - "/comment/"
      - "/theme/"
      - "/user/theme/"
    ROLE_USER:
      - "/user/"
      - "/playlist/"
      - "/artist/"
      - "/song/"
      - "/album/"
      - "/recent/"
      - "/favorite/"
      - "/comment/"
      - "/banner/"
      - "/feedback/"
      - "/theme/"
      - "/user/theme/"

minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:vibe-music-data}
